stages:
  - test
  - build


test:
  stage: test
  image: python:3.10
  script:
    - python3.10 -m venv venv
    - venv/bin/python -m pip install -r requirements.txt
    - venv/bin/python -m pip install -e .[dev]
    - venv/bin/python -m pytest
    - venv/bin/sphinx-build docs public
  coverage: '/\d+\%\s*$/'
  artifacts:
    paths:
      - public
    reports:
      cobertura: coverage.xml
      junit: report.xml
  tags:
    - docker


build:
  stage: build
  image: python:3.10
  script:
    - python3.10 -m venv venv
    - venv/bin/python -m pip install build
    - venv/bin/python -m build .
  artifacts:
    paths:
      - dist
  tags:
    - docker
